<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>


    <xacro:property name="chassis_length" value="0.80"/>
    <xacro:property name="chassis_width" value="0.50"/>
    <xacro:property name="chassis_height" value="0.09"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.053"/>
    <xacro:property name="wheel_thickness" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.40"/>
    <xacro:property name="wheel_offset_y" value="0.27"/>
    <xacro:property name="wheel_offset_z" value="0.0"/>

    <xacro:property name="caster_wheel_radius_left" value="0.038"/>
    <xacro:property name="caster_wheel_mass_left" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x_left" value="0.75"/>
    <xacro:property name="caster_wheel_offset_y_left" value="0.20"/>
    <xacro:property name="caster_wheel_offset_z_left" value="-0.013"/>

    <xacro:property name="caster_wheel_radius_right" value="0.038"/>
    <xacro:property name="caster_wheel_mass_right" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x_right" value="0.75"/>
    <xacro:property name="caster_wheel_offset_y_right" value="-0.20"/>
    <xacro:property name="caster_wheel_offset_z_right" value="-0.013"/>


    <xacro:property name="caster_wheel_radius_left_rear" value="0.038"/>
    <xacro:property name="caster_wheel_mass_left_rear" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x_left_rear" value="0.05"/>
    <xacro:property name="caster_wheel_offset_y_left_rear" value="0.20"/>
    <xacro:property name="caster_wheel_offset_z_left_rear" value="-0.013"/>

    <xacro:property name="caster_wheel_radius_right_rear" value="0.033"/>
    <xacro:property name="caster_wheel_mass_right_rear" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x_right_rear" value="0.05"/>
    <xacro:property name="caster_wheel_offset_y_right_rear" value="-0.20"/>
    <xacro:property name="caster_wheel_offset_z_right_rear" value="-0.013"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />twist_mux
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="point_joint" type="fixed">
        <parent link="left_wheel"/>
        <child link="point"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1"/>
    </joint>


    <link name="point">
        <visual>
            <origin xyz="-0.0 0 0.00" rpy="0 ${1.5} 0"/>
            <geometry>
                <cylinder radius="0.015" length="0.02"/>
            </geometry>
            <material name="red"/>
        </visual>
    </link>

    <gazebo reference="point">
        <material>Gazebo/Red</material>
    </gazebo>


    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>


    <!-- CASTER WHEEL LEFT LINK -->

    <joint name="caster_wheel_joint_left" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel_left"/>
        <origin xyz="${caster_wheel_offset_x_left} ${caster_wheel_offset_y_left}
        ${caster_wheel_offset_z_left}"/>
    </joint>


    <link name="caster_wheel_left">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius_left}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius_left}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass_left}" radius="${caster_wheel_radius_left}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel_left">
        <material>Gazebo/Red</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

<!-- CASTER WHEEL RIGHT LINK -->

    <joint name="caster_wheel_joint_right" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel_right"/>
        <origin xyz="${caster_wheel_offset_x_right} ${caster_wheel_offset_y_right}
        ${caster_wheel_offset_z_right}"/>
    </joint>


    <link name="caster_wheel_right">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius_right}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius_right}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass_right}" radius="${caster_wheel_radius_right}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel_right">
        <material>Gazebo/Red</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>


    <!-- CASTER WHEEL LEFT LINK REAR -->

    <joint name="caster_wheel_joint_left_rear" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel_left_rear"/>
        <origin xyz="${caster_wheel_offset_x_left_rear} ${caster_wheel_offset_y_left_rear}
        ${caster_wheel_offset_z_left}"/>
    </joint>


    <link name="caster_wheel_left_rear">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius_left_rear}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius_left_rear}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass_left_rear}" radius="${caster_wheel_radius_left_rear}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel_left_rear">
        <material>Gazebo/Red</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

<!-- CASTER WHEEL RIGHT LINK REAR -->

    <joint name="caster_wheel_joint_right_rear" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel_right_rear"/>
        <origin xyz="${caster_wheel_offset_x_right_rear} ${caster_wheel_offset_y_right_rear}
        ${caster_wheel_offset_z_right_rear}"/>
    </joint>


    <link name="caster_wheel_right_rear">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius_right_rear}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius_right_rear}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass_right_rear}" radius="${caster_wheel_radius_right_rear}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel_right_rear">
        <material>Gazebo/Red</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <!-- imu -->
    <joint name="imu_joint" type="fixed">
        <parent link="chassis"/>
        <child link="imu_link"/>
        <origin xyz="0.40 0 0.055" rpy="0 0 0"/>
    </joint>

    <link name="imu_link">
        <visual>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.01"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
    </link>
</robot>